name: Build debug apk

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  Make-apk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '11'
    - name: Install fontforge
      run: sudo apt-get install -y fontforge
    - name: Cache debug certificate
      uses: actions/cache@v2
      with:
        path: _build/debug.keystore
        key: debug-keystore
    # Hopefully cached.
#    - name: Debug certificate
#      run: |
#        [[ -f _build/debug.keystore ]] ||
#        nix-shell ./shell.nix --run 'make debug.keystore'
    - name: Build
      run: make
    - name: Save debug apk
      uses: actions/upload-artifact@v2
      with:
        name: debug apk
        path: _build/*.apk
